name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - uses: actions/checkout@v3
    # Install dependencies
    - name: Install dependencies
      run: sudo apt-get install gcc && sudo apt-get install libncurses-dev && sudo apt-get install make
    # Build the project
    - name: Build
      run: make
    # Test rebuild
    - name: Test rebuild
      run: make rebuild
